#!/bin/bash

# read function
. ./regist_function.sh

# arg1: main記述モジュール規格[esm,cjs]
# arg2: main拡張子[.mts,.cts]
# arg3: module記述モジュール規格[esm,cjs]
# arg4: module拡張子[.mts,.cts]
# arg5: running module[module,commonjs]
# arg6: tsconfig.module[e:esnext, n:nodenext, c:commonjs]
# arg7: tsconfig.moduleresolution[n:nodenext, 0:none]
# arg8: test no

mkdir -p ts test
rm -f ts/* test/*

check esm .mts esm .mts module e n 1
check esm .mts esm .mts module e 0 2
check esm .mts esm .mts module n n 3
check esm .mts esm .mts module n 0 4
check esm .mts esm .mts module c n 5
check esm .mts esm .mts module c 0 6
check esm .mts esm .mts commonjs e n 7
check esm .mts esm .mts commonjs e 0 8
check esm .mts esm .mts commonjs n n 9
check esm .mts esm .mts commonjs n 0 10
check esm .mts esm .mts commonjs c n 11
check esm .mts esm .mts commonjs c 0 12
check esm .mts esm .cts module e n 13
check esm .mts esm .cts module e 0 14
check esm .mts esm .cts module n n 15
check esm .mts esm .cts module n 0 16
check esm .mts esm .cts module c n 17
check esm .mts esm .cts module c 0 18
check esm .mts esm .cts commonjs e n 19
check esm .mts esm .cts commonjs e 0 20
check esm .mts esm .cts commonjs n n 21
check esm .mts esm .cts commonjs n 0 22
check esm .mts esm .cts commonjs c n 23
check esm .mts esm .cts commonjs c 0 24
check esm .mts esm .ts module e n 25
check esm .mts esm .ts module e 0 26
check esm .mts esm .ts module n n 27
check esm .mts esm .ts module n 0 28
check esm .mts esm .ts module c n 29
check esm .mts esm .ts module c 0 30
check esm .mts esm .ts commonjs e n 31
check esm .mts esm .ts commonjs e 0 32
check esm .mts esm .ts commonjs n n 33
check esm .mts esm .ts commonjs n 0 34
check esm .mts esm .ts commonjs c n 35
check esm .mts esm .ts commonjs c 0 36
check esm .mts cjs .mts module e n 37
check esm .mts cjs .mts module e 0 38
check esm .mts cjs .mts module n n 39
check esm .mts cjs .mts module n 0 40
check esm .mts cjs .mts module c n 41
check esm .mts cjs .mts module c 0 42
check esm .mts cjs .mts commonjs e n 43
check esm .mts cjs .mts commonjs e 0 44
check esm .mts cjs .mts commonjs n n 45
check esm .mts cjs .mts commonjs n 0 46
check esm .mts cjs .mts commonjs c n 47
check esm .mts cjs .mts commonjs c 0 48
check esm .mts cjs .cts module e n 49
check esm .mts cjs .cts module e 0 50
check esm .mts cjs .cts module n n 51
check esm .mts cjs .cts module n 0 52
check esm .mts cjs .cts module c n 53
check esm .mts cjs .cts module c 0 54
check esm .mts cjs .cts commonjs e n 55
check esm .mts cjs .cts commonjs e 0 56
check esm .mts cjs .cts commonjs n n 57
check esm .mts cjs .cts commonjs n 0 58
check esm .mts cjs .cts commonjs c n 59
check esm .mts cjs .cts commonjs c 0 60
check esm .mts cjs .ts module e n 61
check esm .mts cjs .ts module e 0 62
check esm .mts cjs .ts module n n 63
check esm .mts cjs .ts module n 0 64
check esm .mts cjs .ts module c n 65
check esm .mts cjs .ts module c 0 66
check esm .mts cjs .ts commonjs e n 67
check esm .mts cjs .ts commonjs e 0 68
check esm .mts cjs .ts commonjs n n 69
check esm .mts cjs .ts commonjs n 0 70
check esm .mts cjs .ts commonjs c n 71
check esm .mts cjs .ts commonjs c 0 72
check esm .cts esm .mts module e n 73
check esm .cts esm .mts module e 0 74
check esm .cts esm .mts module n n 75
check esm .cts esm .mts module n 0 76
check esm .cts esm .mts module c n 77
check esm .cts esm .mts module c 0 78
check esm .cts esm .mts commonjs e n 79
check esm .cts esm .mts commonjs e 0 80
check esm .cts esm .mts commonjs n n 81
check esm .cts esm .mts commonjs n 0 82
check esm .cts esm .mts commonjs c n 83
check esm .cts esm .mts commonjs c 0 84
check esm .cts esm .cts module e n 85
check esm .cts esm .cts module e 0 86
check esm .cts esm .cts module n n 87
check esm .cts esm .cts module n 0 88
check esm .cts esm .cts module c n 89
check esm .cts esm .cts module c 0 90
check esm .cts esm .cts commonjs e n 91
check esm .cts esm .cts commonjs e 0 92
check esm .cts esm .cts commonjs n n 93
check esm .cts esm .cts commonjs n 0 94
check esm .cts esm .cts commonjs c n 95
check esm .cts esm .cts commonjs c 0 96
check esm .cts esm .ts module e n 97
check esm .cts esm .ts module e 0 98
check esm .cts esm .ts module n n 99
check esm .cts esm .ts module n 0 100
check esm .cts esm .ts module c n 101
check esm .cts esm .ts module c 0 102
check esm .cts esm .ts commonjs e n 103
check esm .cts esm .ts commonjs e 0 104
check esm .cts esm .ts commonjs n n 105
check esm .cts esm .ts commonjs n 0 106
check esm .cts esm .ts commonjs c n 107
check esm .cts esm .ts commonjs c 0 108
check esm .cts cjs .mts module e n 109
check esm .cts cjs .mts module e 0 110
check esm .cts cjs .mts module n n 111
check esm .cts cjs .mts module n 0 112
check esm .cts cjs .mts module c n 113
check esm .cts cjs .mts module c 0 114
check esm .cts cjs .mts commonjs e n 115
check esm .cts cjs .mts commonjs e 0 116
check esm .cts cjs .mts commonjs n n 117
check esm .cts cjs .mts commonjs n 0 118
check esm .cts cjs .mts commonjs c n 119
check esm .cts cjs .mts commonjs c 0 120
check esm .cts cjs .cts module e n 121
check esm .cts cjs .cts module e 0 122
check esm .cts cjs .cts module n n 123
check esm .cts cjs .cts module n 0 124
check esm .cts cjs .cts module c n 125
check esm .cts cjs .cts module c 0 126
check esm .cts cjs .cts commonjs e n 127
check esm .cts cjs .cts commonjs e 0 128
check esm .cts cjs .cts commonjs n n 129
check esm .cts cjs .cts commonjs n 0 130
check esm .cts cjs .cts commonjs c n 131
check esm .cts cjs .cts commonjs c 0 132
check esm .cts cjs .ts module e n 133
check esm .cts cjs .ts module e 0 134
check esm .cts cjs .ts module n n 135
check esm .cts cjs .ts module n 0 136
check esm .cts cjs .ts module c n 137
check esm .cts cjs .ts module c 0 138
check esm .cts cjs .ts commonjs e n 139
check esm .cts cjs .ts commonjs e 0 140
check esm .cts cjs .ts commonjs n n 141
check esm .cts cjs .ts commonjs n 0 142
check esm .cts cjs .ts commonjs c n 143
check esm .cts cjs .ts commonjs c 0 144
check esm .ts esm .mts module e n 145
check esm .ts esm .mts module e 0 146
check esm .ts esm .mts module n n 147
check esm .ts esm .mts module n 0 148
check esm .ts esm .mts module c n 149
check esm .ts esm .mts module c 0 150
check esm .ts esm .mts commonjs e n 151
check esm .ts esm .mts commonjs e 0 152
check esm .ts esm .mts commonjs n n 153
check esm .ts esm .mts commonjs n 0 154
check esm .ts esm .mts commonjs c n 155
check esm .ts esm .mts commonjs c 0 156
check esm .ts esm .cts module e n 157
check esm .ts esm .cts module e 0 158
check esm .ts esm .cts module n n 159
check esm .ts esm .cts module n 0 160
check esm .ts esm .cts module c n 161
check esm .ts esm .cts module c 0 162
check esm .ts esm .cts commonjs e n 163
check esm .ts esm .cts commonjs e 0 164
check esm .ts esm .cts commonjs n n 165
check esm .ts esm .cts commonjs n 0 166
check esm .ts esm .cts commonjs c n 167
check esm .ts esm .cts commonjs c 0 168
check esm .ts esm .ts module e n 169
check esm .ts esm .ts module e 0 170
check esm .ts esm .ts module n n 171
check esm .ts esm .ts module n 0 172
check esm .ts esm .ts module c n 173
check esm .ts esm .ts module c 0 174
check esm .ts esm .ts commonjs e n 175
check esm .ts esm .ts commonjs e 0 176
check esm .ts esm .ts commonjs n n 177
check esm .ts esm .ts commonjs n 0 178
check esm .ts esm .ts commonjs c n 179
check esm .ts esm .ts commonjs c 0 180
check esm .ts cjs .mts module e n 181
check esm .ts cjs .mts module e 0 182
check esm .ts cjs .mts module n n 183
check esm .ts cjs .mts module n 0 184
check esm .ts cjs .mts module c n 185
check esm .ts cjs .mts module c 0 186
check esm .ts cjs .mts commonjs e n 187
check esm .ts cjs .mts commonjs e 0 188
check esm .ts cjs .mts commonjs n n 189
check esm .ts cjs .mts commonjs n 0 190
check esm .ts cjs .mts commonjs c n 191
check esm .ts cjs .mts commonjs c 0 192
check esm .ts cjs .cts module e n 193
check esm .ts cjs .cts module e 0 194
check esm .ts cjs .cts module n n 195
check esm .ts cjs .cts module n 0 196
check esm .ts cjs .cts module c n 197
check esm .ts cjs .cts module c 0 198
check esm .ts cjs .cts commonjs e n 199
check esm .ts cjs .cts commonjs e 0 200
check esm .ts cjs .cts commonjs n n 201
check esm .ts cjs .cts commonjs n 0 202
check esm .ts cjs .cts commonjs c n 203
check esm .ts cjs .cts commonjs c 0 204
check esm .ts cjs .ts module e n 205
check esm .ts cjs .ts module e 0 206
check esm .ts cjs .ts module n n 207
check esm .ts cjs .ts module n 0 208
check esm .ts cjs .ts module c n 209
check esm .ts cjs .ts module c 0 210
check esm .ts cjs .ts commonjs e n 211
check esm .ts cjs .ts commonjs e 0 212
check esm .ts cjs .ts commonjs n n 213
check esm .ts cjs .ts commonjs n 0 214
check esm .ts cjs .ts commonjs c n 215
check esm .ts cjs .ts commonjs c 0 216
check cjs .mts esm .mts module e n 217
check cjs .mts esm .mts module e 0 218
check cjs .mts esm .mts module n n 219
check cjs .mts esm .mts module n 0 220
check cjs .mts esm .mts module c n 221
check cjs .mts esm .mts module c 0 222
check cjs .mts esm .mts commonjs e n 223
check cjs .mts esm .mts commonjs e 0 224
check cjs .mts esm .mts commonjs n n 225
check cjs .mts esm .mts commonjs n 0 226
check cjs .mts esm .mts commonjs c n 227
check cjs .mts esm .mts commonjs c 0 228
check cjs .mts esm .cts module e n 229
check cjs .mts esm .cts module e 0 230
check cjs .mts esm .cts module n n 231
check cjs .mts esm .cts module n 0 232
check cjs .mts esm .cts module c n 233
check cjs .mts esm .cts module c 0 234
check cjs .mts esm .cts commonjs e n 235
check cjs .mts esm .cts commonjs e 0 236
check cjs .mts esm .cts commonjs n n 237
check cjs .mts esm .cts commonjs n 0 238
check cjs .mts esm .cts commonjs c n 239
check cjs .mts esm .cts commonjs c 0 240
check cjs .mts esm .ts module e n 241
check cjs .mts esm .ts module e 0 242
check cjs .mts esm .ts module n n 243
check cjs .mts esm .ts module n 0 244
check cjs .mts esm .ts module c n 245
check cjs .mts esm .ts module c 0 246
check cjs .mts esm .ts commonjs e n 247
check cjs .mts esm .ts commonjs e 0 248
check cjs .mts esm .ts commonjs n n 249
check cjs .mts esm .ts commonjs n 0 250
check cjs .mts esm .ts commonjs c n 251
check cjs .mts esm .ts commonjs c 0 252
check cjs .mts cjs .mts module e n 253
check cjs .mts cjs .mts module e 0 254
check cjs .mts cjs .mts module n n 255
check cjs .mts cjs .mts module n 0 256
check cjs .mts cjs .mts module c n 257
check cjs .mts cjs .mts module c 0 258
check cjs .mts cjs .mts commonjs e n 259
check cjs .mts cjs .mts commonjs e 0 260
check cjs .mts cjs .mts commonjs n n 261
check cjs .mts cjs .mts commonjs n 0 262
check cjs .mts cjs .mts commonjs c n 263
check cjs .mts cjs .mts commonjs c 0 264
check cjs .mts cjs .cts module e n 265
check cjs .mts cjs .cts module e 0 266
check cjs .mts cjs .cts module n n 267
check cjs .mts cjs .cts module n 0 268
check cjs .mts cjs .cts module c n 269
check cjs .mts cjs .cts module c 0 270
check cjs .mts cjs .cts commonjs e n 271
check cjs .mts cjs .cts commonjs e 0 272
check cjs .mts cjs .cts commonjs n n 273
check cjs .mts cjs .cts commonjs n 0 274
check cjs .mts cjs .cts commonjs c n 275
check cjs .mts cjs .cts commonjs c 0 276
check cjs .mts cjs .ts module e n 277
check cjs .mts cjs .ts module e 0 278
check cjs .mts cjs .ts module n n 279
check cjs .mts cjs .ts module n 0 280
check cjs .mts cjs .ts module c n 281
check cjs .mts cjs .ts module c 0 282
check cjs .mts cjs .ts commonjs e n 283
check cjs .mts cjs .ts commonjs e 0 284
check cjs .mts cjs .ts commonjs n n 285
check cjs .mts cjs .ts commonjs n 0 286
check cjs .mts cjs .ts commonjs c n 287
check cjs .mts cjs .ts commonjs c 0 288
check cjs .cts esm .mts module e n 289
check cjs .cts esm .mts module e 0 290
check cjs .cts esm .mts module n n 291
check cjs .cts esm .mts module n 0 292
check cjs .cts esm .mts module c n 293
check cjs .cts esm .mts module c 0 294
check cjs .cts esm .mts commonjs e n 295
check cjs .cts esm .mts commonjs e 0 296
check cjs .cts esm .mts commonjs n n 297
check cjs .cts esm .mts commonjs n 0 298
check cjs .cts esm .mts commonjs c n 299
check cjs .cts esm .mts commonjs c 0 300
check cjs .cts esm .cts module e n 301
check cjs .cts esm .cts module e 0 302
check cjs .cts esm .cts module n n 303
check cjs .cts esm .cts module n 0 304
check cjs .cts esm .cts module c n 305
check cjs .cts esm .cts module c 0 306
check cjs .cts esm .cts commonjs e n 307
check cjs .cts esm .cts commonjs e 0 308
check cjs .cts esm .cts commonjs n n 309
check cjs .cts esm .cts commonjs n 0 310
check cjs .cts esm .cts commonjs c n 311
check cjs .cts esm .cts commonjs c 0 312
check cjs .cts esm .ts module e n 313
check cjs .cts esm .ts module e 0 314
check cjs .cts esm .ts module n n 315
check cjs .cts esm .ts module n 0 316
check cjs .cts esm .ts module c n 317
check cjs .cts esm .ts module c 0 318
check cjs .cts esm .ts commonjs e n 319
check cjs .cts esm .ts commonjs e 0 320
check cjs .cts esm .ts commonjs n n 321
check cjs .cts esm .ts commonjs n 0 322
check cjs .cts esm .ts commonjs c n 323
check cjs .cts esm .ts commonjs c 0 324
check cjs .cts cjs .mts module e n 325
check cjs .cts cjs .mts module e 0 326
check cjs .cts cjs .mts module n n 327
check cjs .cts cjs .mts module n 0 328
check cjs .cts cjs .mts module c n 329
check cjs .cts cjs .mts module c 0 330
check cjs .cts cjs .mts commonjs e n 331
check cjs .cts cjs .mts commonjs e 0 332
check cjs .cts cjs .mts commonjs n n 333
check cjs .cts cjs .mts commonjs n 0 334
check cjs .cts cjs .mts commonjs c n 335
check cjs .cts cjs .mts commonjs c 0 336
check cjs .cts cjs .cts module e n 337
check cjs .cts cjs .cts module e 0 338
check cjs .cts cjs .cts module n n 339
check cjs .cts cjs .cts module n 0 340
check cjs .cts cjs .cts module c n 341
check cjs .cts cjs .cts module c 0 342
check cjs .cts cjs .cts commonjs e n 343
check cjs .cts cjs .cts commonjs e 0 344
check cjs .cts cjs .cts commonjs n n 345
check cjs .cts cjs .cts commonjs n 0 346
check cjs .cts cjs .cts commonjs c n 347
check cjs .cts cjs .cts commonjs c 0 348
check cjs .cts cjs .ts module e n 349
check cjs .cts cjs .ts module e 0 350
check cjs .cts cjs .ts module n n 351
check cjs .cts cjs .ts module n 0 352
check cjs .cts cjs .ts module c n 353
check cjs .cts cjs .ts module c 0 354
check cjs .cts cjs .ts commonjs e n 355
check cjs .cts cjs .ts commonjs e 0 356
check cjs .cts cjs .ts commonjs n n 357
check cjs .cts cjs .ts commonjs n 0 358
check cjs .cts cjs .ts commonjs c n 359
check cjs .cts cjs .ts commonjs c 0 360
check cjs .ts esm .mts module e n 361
check cjs .ts esm .mts module e 0 362
check cjs .ts esm .mts module n n 363
check cjs .ts esm .mts module n 0 364
check cjs .ts esm .mts module c n 365
check cjs .ts esm .mts module c 0 366
check cjs .ts esm .mts commonjs e n 367
check cjs .ts esm .mts commonjs e 0 368
check cjs .ts esm .mts commonjs n n 369
check cjs .ts esm .mts commonjs n 0 370
check cjs .ts esm .mts commonjs c n 371
check cjs .ts esm .mts commonjs c 0 372
check cjs .ts esm .cts module e n 373
check cjs .ts esm .cts module e 0 374
check cjs .ts esm .cts module n n 375
check cjs .ts esm .cts module n 0 376
check cjs .ts esm .cts module c n 377
check cjs .ts esm .cts module c 0 378
check cjs .ts esm .cts commonjs e n 379
check cjs .ts esm .cts commonjs e 0 380
check cjs .ts esm .cts commonjs n n 381
check cjs .ts esm .cts commonjs n 0 382
check cjs .ts esm .cts commonjs c n 383
check cjs .ts esm .cts commonjs c 0 384
check cjs .ts esm .ts module e n 385
check cjs .ts esm .ts module e 0 386
check cjs .ts esm .ts module n n 387
check cjs .ts esm .ts module n 0 388
check cjs .ts esm .ts module c n 389
check cjs .ts esm .ts module c 0 390
check cjs .ts esm .ts commonjs e n 391
check cjs .ts esm .ts commonjs e 0 392
check cjs .ts esm .ts commonjs n n 393
check cjs .ts esm .ts commonjs n 0 394
check cjs .ts esm .ts commonjs c n 395
check cjs .ts esm .ts commonjs c 0 396
check cjs .ts cjs .mts module e n 397
check cjs .ts cjs .mts module e 0 398
check cjs .ts cjs .mts module n n 399
check cjs .ts cjs .mts module n 0 400
check cjs .ts cjs .mts module c n 401
check cjs .ts cjs .mts module c 0 402
check cjs .ts cjs .mts commonjs e n 403
check cjs .ts cjs .mts commonjs e 0 404
check cjs .ts cjs .mts commonjs n n 405
check cjs .ts cjs .mts commonjs n 0 406
check cjs .ts cjs .mts commonjs c n 407
check cjs .ts cjs .mts commonjs c 0 408
check cjs .ts cjs .cts module e n 409
check cjs .ts cjs .cts module e 0 410
check cjs .ts cjs .cts module n n 411
check cjs .ts cjs .cts module n 0 412
check cjs .ts cjs .cts module c n 413
check cjs .ts cjs .cts module c 0 414
check cjs .ts cjs .cts commonjs e n 415
check cjs .ts cjs .cts commonjs e 0 416
check cjs .ts cjs .cts commonjs n n 417
check cjs .ts cjs .cts commonjs n 0 418
check cjs .ts cjs .cts commonjs c n 419
check cjs .ts cjs .cts commonjs c 0 420
check cjs .ts cjs .ts module e n 421
check cjs .ts cjs .ts module e 0 422
check cjs .ts cjs .ts module n n 423
check cjs .ts cjs .ts module n 0 424
check cjs .ts cjs .ts module c n 425
check cjs .ts cjs .ts module c 0 426
check cjs .ts cjs .ts commonjs e n 427
check cjs .ts cjs .ts commonjs e 0 428
check cjs .ts cjs .ts commonjs n n 429
check cjs .ts cjs .ts commonjs n 0 430
check cjs .ts cjs .ts commonjs c n 431
check cjs .ts cjs .ts commonjs c 0 432